kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ekspose-cluster
nodes:
- role: control-plane
  image: kindest/node:latest
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 4443
    protocol: TCP
- role: worker
  image: kindest/node:latest
- role: worker
  image: kindest/node:latest